MethodsFromMahoutTests: MethodsFromMahoutTests.java
	javac MethodsFromMahoutTests.java

MethodsFromApacheMathTest: MethodsFromApacheMathTests.java
	javac MethodsFromApacheMathTests.java

MethodsFromColtTests: MethodsFromColtTests.java
	javac MethodsFromColtTests.java

MethodCollection2Tests: MethodCollection2Tests.java
	javac MethodCollection2Tests.java

TestClass: TestClass.java
	javac TestClass.java
