MethodsFromMahoutTests.class: MethodsFromMahoutTests.java
	javac MethodsFromMahoutTests.java

MethodsFromApacheMathTest.class: MethodsFromApacheMathTests.java
	javac MethodsFromApacheMathTests.java

MethodsFromColtTests.class: MethodsFromColtTests.java
	javac MethodsFromColtTests.java

MethodCollection2Tests.class: MethodCollection2Tests.java
	javac MethodCollection2Tests.java

TestClass.class: TestClass.java
	javac TestClass.java
